### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by Evilbolzen** [gipplab/Electronic-Laboratory-Notebook#2]
Hi,

When I try to compose the yml, I do get this error:
`(root) Additional property web is not allowed`

So far I wasn't able to figure out the issue, so I tried a clean docker installation in a VM as well, but the error stays, All python requirements are fullfilled as well and the most common suggestion was that there is a indentation mistake in the yaml.

For me, it looks fine from that point, but I am far from being an expert in yml files. Also tried different methods to get the yml file (raw download, git clone, copy paste), changes nothing.

I also checked if my docker is okay, I could compose yml for containers without any errors, so I guess this might not be the issue.

Do you have any suggestion?
Best regards

PS: Forgot to mention:
OS: Windows 10 21H2
Python 3.8.5 (via Anaconda)
Docker: v4.12.0

**Comment by Evilbolzen** [comment]
And I fixed it,

didn't saw that the services tag was missing. After adding it docker is composing it

**Comment by SimonSchubotz** [comment]
Thank you for pointing this out. I just tried to run the lab book with docker and did not get any error on my PC. Maybe you can write in more detail about how you fixed it so I can include it in the git.

**Comment by Evilbolzen** [comment]
Hi
basically I just added the single tag as shown below (for some reason the code doesn't show the right indentation if I add it as a code, so plain text only):

services:
web:
    build: .
    environment:
        MYENV: Labbook
    volumes:
        - .:/code
  web_migrate:
    extends:
        service: web
    command: python manage.py migrate
  web_run:
    extends:
        service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"

**Comment by SimonSchubotz** [comment]
Ok, I then also needed the Version. I updated the git accordingly.
